# Generated by Django 4.2.7 on 2023-11-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bano_name', models.CharField(default='Nombre Mueble Baño', max_length=50)),
                ('descripcion', models.CharField(default='Descripcion Mueble Baño', max_length=256)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0.0)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('update_baño', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Cocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocina_name', models.CharField(default='Nombre Mueble Cocina', max_length=50)),
                ('descripcion', models.CharField(default='Descripcion Mueble Cocina', max_length=256)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0.0)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('update_cocina', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comedor_name', models.CharField(default='Nombre Mueble Comedor', max_length=50)),
                ('descripcion', models.CharField(default='Descripcion Mueble Comedor', max_length=256)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0.0)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('update_comedor', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina_name', models.CharField(default='Nombre Mueble Oficina', max_length=50)),
                ('descripcion', models.CharField(default='Descripcion Mueble Oficina', max_length=256)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0.0)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('update_oficina', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Recamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recamara_name', models.CharField(default='Nombre Mueble Recamara', max_length=50)),
                ('descripcion', models.CharField(default='Descripcion Mueble Recamara', max_length=256)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0.0)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('update_recamara', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala_name', models.CharField(default='Nombre Mueble Sala', max_length=50)),
                ('descripcion', models.CharField(default='Descripcion Mueble Sala', max_length=256)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0.0)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('update_sala', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=16)),
            ],
        ),
    ]
