# Generated by Django 4.2.7 on 2023-11-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bano',
            old_name='slug',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='cocina',
            old_name='slug',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='comedor',
            old_name='slug',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='oficina',
            old_name='slug',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='recamara',
            old_name='slug',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='slug',
            new_name='codigo',
        ),
    ]
