# Generated by Django 4.2.7 on 2023-11-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cocina_imagen_alter_comedor_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bano',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Banos'),
        ),
    ]
