# Generated by Django 4.2.7 on 2023-11-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bano_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bano',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/M-Banos'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/M-Cocinas/'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/M-Comedores/'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/M-Oficinas/'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/M-Recamara/'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/M-Sala/'),
        ),
    ]
