# Generated by Django 4.2.7 on 2023-11-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bano_imagen_alter_cocina_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bano',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Banos/'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Cocinas/'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Comedores/'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Oficinas/'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Recamara/'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Sala/'),
        ),
    ]
