# Generated by Django 4.2.7 on 2023-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bano_imagen_alter_cocina_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bano',
            name='bano_name',
            field=models.CharField(default='Nombre Mueble Baño', max_length=50, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='bano',
            name='codigo',
            field=models.SlugField(max_length=16, verbose_name='Código:'),
        ),
        migrations.AlterField(
            model_name='bano',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Baño', max_length=256, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='bano',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Banos/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='bano',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='Precio:'),
        ),
        migrations.AlterField(
            model_name='bano',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='bano',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock:'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='cocina_name',
            field=models.CharField(default='Nombre Mueble Cocina', max_length=50, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='codigo',
            field=models.SlugField(max_length=16, verbose_name='Código:'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Cocina', max_length=256, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Cocinas/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='Precio:'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock:'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='codigo',
            field=models.SlugField(max_length=16, verbose_name='Código:'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='comedor_name',
            field=models.CharField(default='Nombre Mueble Comedor', max_length=50, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Comedor', max_length=256, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Comedores/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='Precio:'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock:'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='codigo',
            field=models.SlugField(max_length=16, verbose_name='Código:'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Recamara', max_length=256, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Recamara/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='Precio:'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='recamara_name',
            field=models.CharField(default='Nombre Mueble Recamara', max_length=50, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock:'),
        ),
    ]
