# Generated by Django 4.2.7 on 2023-11-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_bano_bano_name_alter_bano_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='codigo',
            field=models.SlugField(max_length=16, verbose_name='Código:'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Oficina', max_length=256, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Oficinas/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='oficina_name',
            field=models.CharField(default='Nombre Mueble Oficina', max_length=50, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='Precio:'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='codigo',
            field=models.SlugField(max_length=16, verbose_name='Código:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Sala', max_length=256, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Sala/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='Precio:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='sala_name',
            field=models.CharField(default='Nombre Mueble Sala', max_length=50, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock:'),
        ),
    ]
