# Generated by Django 4.2.7 on 2023-11-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_bano_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bano',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='M-Banos/', verbose_name='Imagen:'),
        ),
    ]
