# Generated by Django 4.2.7 on 2023-11-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_bano_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bano',
            name='imagen',
            field=models.ImageField(default='/static/images/logos/Logo.png', upload_to='M-Banos/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='imagen',
            field=models.ImageField(default='/static/images/logos/Logo.png', upload_to='M-Cocinas/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='imagen',
            field=models.ImageField(default='/static/images/logos/Logo.png', upload_to='M-Comedores/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='imagen',
            field=models.ImageField(default='/static/images/logos/Logo.png', upload_to='M-Oficinas/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='imagen',
            field=models.ImageField(default='/static/images/logos/Logo.png', upload_to='M-Recamara/', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='imagen',
            field=models.ImageField(default='/static/images/logos/Logo.png', upload_to='M-Sala/', verbose_name='Imagen:'),
        ),
    ]
