# Generated by Django 4.2.7 on 2023-11-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_bano_imagen_alter_cocina_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bano',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Baño', max_length=300, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Cocina', max_length=300, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Comedor', max_length=300, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Oficina', max_length=300, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='recamara',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Recamara', max_length=300, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='descripcion',
            field=models.CharField(default='Descripcion Mueble Sala', max_length=300, verbose_name='Descripcion:'),
        ),
    ]
