# Generated by Django 4.2.7 on 2023-11-26 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Generic User', max_length=32, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(blank=True, default='user@email.com', max_length=254, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='users/profiles')),
                ('bio', models.CharField(blank=True, default='I LOVE THIS APP', max_length=256, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
